version: '3.8'

services:
  php:
    build: .
    container_name: php_app
    volumes:
      - ./ass2/jobs:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000 -t /var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: Assignment2
      DB_USER: user
      DB_PASS: password

  mysql:
    image: mariadb:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Assignment2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer_ui
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysqldata:
